//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS_DIMANCHE
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine_1_production
    {
        public int idmachine_1_production { get; set; }
        public Nullable<System.DateTime> debut { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public string of_1 { get; set; }
        public string of_2 { get; set; }
        public string ref_1 { get; set; }
        public string ref_2 { get; set; }
        public string moule { get; set; }
        public string matiere { get; set; }
        public string palette { get; set; }
        public Nullable<int> empreinte { get; set; }
        public string description { get; set; }
        public Nullable<int> ref_1_total { get; set; }
        public Nullable<int> ref_2_total { get; set; }
        public Nullable<int> ref_1_rebut { get; set; }
        public Nullable<int> ref_2_rebut { get; set; }
        public Nullable<double> ref_1_qualite { get; set; }
        public Nullable<double> ref_2_qualite { get; set; }
    }
}
