//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS_DIMANCHE
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine_1_rebut
    {
        public int idmachine_1_rebut { get; set; }
        public Nullable<int> quantité { get; set; }
        public string rebut { get; set; }
        public Nullable<System.DateTime> temps { get; set; }
        public string of { get; set; }
        public string produit { get; set; }
    }
}
