//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS_DIMANCHE
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine_1_trs
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> temps_brut { get; set; }
        public Nullable<double> temps_requis { get; set; }
        public Nullable<double> disponibilite { get; set; }
        public Nullable<int> qte_produite { get; set; }
        public Nullable<int> qte_acceptee { get; set; }
        public Nullable<double> qualite { get; set; }
        public Nullable<double> cadence_reele { get; set; }
        public Nullable<double> cadence_therorique { get; set; }
        public Nullable<double> performance { get; set; }
        public Nullable<double> TRS { get; set; }
        public string user { get; set; }
        public string moule { get; set; }
        public string produit_1 { get; set; }
        public string produit_2 { get; set; }
        public Nullable<int> empreinte { get; set; }
        public string matiere { get; set; }
        public string palette { get; set; }
        public string equipe { get; set; }
        public string of_2 { get; set; }
        public string of_1 { get; set; }
        public Nullable<double> qualite_produit_1 { get; set; }
        public Nullable<double> qualite_produit_2 { get; set; }
    }
}
