//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS_DIMANCHE
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine_1_arrets
    {
        public int id { get; set; }
        public string date { get; set; }
        public string arret { get; set; }
        public Nullable<System.DateTime> debut { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public Nullable<int> duree { get; set; }
        public string of_1 { get; set; }
        public string of_2 { get; set; }
        public string type_arret { get; set; }
    }
}
