//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRS_DIMANCHE
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int id { get; set; }
        public string produit1 { get; set; }
        public int tempsdecycle { get; set; }
        public string Reference { get; set; }
    }
}
